// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v310 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v310));
        
        string IMigrationMetadata.Id
        {
            get { return "201309261612260_v3.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
