// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v303 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v303));
        
        string IMigrationMetadata.Id
        {
            get { return "201309182029095_v3.0.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
