// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v320 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v320));
        
        string IMigrationMetadata.Id
        {
            get { return "201403311956281_v3.2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
