// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v421 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v421));
        
        string IMigrationMetadata.Id
        {
            get { return "201612072037289_v4.2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
