// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v410 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v410));
        
        string IMigrationMetadata.Id
        {
            get { return "201609221622180_v4.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
