// <auto-generated />
namespace GalleryServer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v443 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v443));
        
        string IMigrationMetadata.Id
        {
            get { return "201807042108481_v4.4.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
