using GalleryServer.Web.Entity;

namespace GalleryServer.Web.Controller
{
  /// <summary>
  /// Contains functionality for returning resources in a form that can be consumed on the client.
  /// </summary>
  public static class ResourceController
  {
    /// <summary>
    /// Gets an object containing string resources. The object can be JSON parsed and sent to the client.
    /// </summary>
    /// <returns>An instance of <see cref="Resource" />.</returns>
    public static Resource GetResourceEntity()
    {
      return new Resource
      {
        HdrSrchBtn = Resources.GalleryServer.Search_Button_Text,
        HdrSrchBtnTt = Resources.GalleryServer.Search_Button_Tooltip,
        HdrSrchBtnHdr = Resources.GalleryServer.Search_Search_Label,
        HdrSrchBtnPh = Resources.GalleryServer.Search_Instructions,
        HdrSrchTitleCap = Resources.GalleryServer.Search_Type_Title,
        HdrSrchTags = Resources.GalleryServer.Search_Type_Tags,
        HdrSrchPeople = Resources.GalleryServer.Search_Type_People,
        HdrSrchAll = Resources.GalleryServer.Search_Type_Everything,
        HdrMyAccountTt = Resources.GalleryServer.Login_My_Account_Link_Text,
        HdrLoginLinkText = Resources.GalleryServer.Login_Button_Text,
        HdrLogoutTt = Resources.GalleryServer.Login_Logout_Text,
        HdrCreateAccountLinkText = Resources.GalleryServer.Login_Create_Account_Text,
        LpRecent = Resources.GalleryServer.UC_LeftPane_RecentlyAdded_Text,
        LpTopRated = Resources.GalleryServer.UC_LeftPane_TopRated_Text,
        LpTags = Resources.GalleryServer.UC_LeftPane_Tags_Text,
        LpPeople = Resources.GalleryServer.UC_LeftPane_People_Text,
        AbmPgrFirstTt = Resources.GalleryServer.UC_ThumbnailView_Pager_First_Tooltip,
        AbmPgrLastTt = Resources.GalleryServer.UC_ThumbnailView_Pager_Last_Tooltip,
        AbmPfx = Resources.GalleryServer.Site_Album_Lbl,
        AbmIsPvtTt = Resources.GalleryServer.UC_Album_Is_Private_Tt,
        AbmNotPvtTt = Resources.GalleryServer.UC_Album_Not_Private_Tt,
        AbmAnonDisabledTt = Resources.GalleryServer.UC_Album_Anon_Disabled_Tt,
        AbmAnonDisabledTitle = Resources.GalleryServer.UC_Album_Anon_Disabled_Title,
        AbmAnonDisabledMsg = Resources.GalleryServer.UC_Album_Anon_Disabled_Msg,
        AbmPvtChngd = Resources.GalleryServer.UC_Album_Visibility_Changed_Tt,
        AbmPvtHdr = Resources.GalleryServer.UC_Album_Visibility_Changed_Hdr,
        AbmPvtDtl = Resources.GalleryServer.UC_Album_Visibility_Changed_Dtl,
        //AbmOwnrTt = Resources.GalleryServer.UC_Album_Assign_Owner_Tt,
        //AbmOwnr = Resources.GalleryServer.UC_Album_Owner_Tt,
        //AbmOwnrDtl = Resources.GalleryServer.UC_Album_Owner_Dtl,
        AbmOwnrLbl = Resources.GalleryServer.UC_Album_Owner_Lbl,
        AbmOwnrInhtd = Resources.GalleryServer.UC_Album_Inherited_Owners_Lbl,
        //AbmOwnrChngd = Resources.GalleryServer.UC_Album_Owner_Changed_Hdr,
        //AbmOwnrClrd = Resources.GalleryServer.UC_Album_Owner_Removed,
        //AbmOwnrChngdDtl = Resources.GalleryServer.UC_Album_Owner_Changed_Dtl,
        AbmOwnrTtDtl = Resources.GalleryServer.UC_Album_Owner_Tt_Dtl,
        AbmRssTt = Resources.GalleryServer.UC_Album_Rss_Tt,
        AbmPgrNextTt = Resources.GalleryServer.UC_ThumbnailView_Pager_Next_Tooltip,
        AbmPgrPrevTt = Resources.GalleryServer.UC_ThumbnailView_Pager_Previous_Tooltip,
        AbmPgrStatus = Resources.GalleryServer.UC_ThumbnailView_Pager_Status,
        AbmNumObjSuffix = Resources.GalleryServer.UC_Album_Num_Obj_Suffix,
        AbmShareAlbum = Resources.GalleryServer.UC_Album_Share_Hdr,
        AbmLinkToAlbum = Resources.GalleryServer.UC_Album_Link_Hdr,
        AbmDwnldZip = Resources.GalleryServer.UC_ThumbnailView_Album_Download_Zip_Tooltip,
        AbmRvsSortTt = Resources.GalleryServer.UC_Album_Reverse_Sort_Tt,
        AbmSortbyTt = Resources.GalleryServer.UC_Album_Sort_By_Tt,
        AbmSortbyCustom = Resources.GalleryServer.UC_Album_Sort_By_Custom,
        AbmSortbyTitle = Resources.GalleryServer.UC_Album_Sort_By_Title,
        AbmSortbyRating = Resources.GalleryServer.UC_Album_Sort_By_Rating,
        AbmSortbyDatePictureTaken = Resources.GalleryServer.UC_Album_Sort_By_DatePictureTaken,
        AbmSortbyDateAdded = Resources.GalleryServer.UC_Album_Sort_By_DateAdded,
        AbmSortbyFilename = Resources.GalleryServer.UC_Album_Sort_By_Filename,
        AbmNoObj = Resources.GalleryServer.UC_ThumbnailView_Intro_Text_No_Objects,
        AbmAddObj = Resources.GalleryServer.UC_ThumbnailView_Intro_Text_Add_Objects,
        AbmDefTitle = Resources.GalleryServer.Admin_Albums_NewAlbumDefaultName,

        MoPrev = Resources.GalleryServer.UC_MoView_Prev_Tt,
        MoNext = Resources.GalleryServer.UC_MoView_Next_Tt,
        MoTbEmbed = Resources.GalleryServer.UC_MoView_Tb_Download_Tt,
        //MoTbSsStart = Resources.GalleryServer.UC_MoView_Tb_Ss_Start_Tt,
        //MoTbSsStop = Resources.GalleryServer.UC_MoView_Tb_Ss_Pause_Tt,
        MoTbMove = Resources.GalleryServer.UC_MoView_Tb_Move_Tt,
        MoTbCopy = Resources.GalleryServer.UC_MoView_Tb_Copy_Tt,
        MoTbRotate = Resources.GalleryServer.UC_MoView_Tb_Rotate_Tt,
        MoTbDelete = Resources.GalleryServer.UC_MoView_Tb_Delete_Tt,
        MoPosSptr = Resources.GalleryServer.UC_MediaObjectView_Position_Separator_Text,
        MoShare = Resources.GalleryServer.UC_MoView_Tb_Share_Tt,
        MoShareThisPage = Resources.GalleryServer.UC_MoView_Tb_Share_Url_Lbl,
        MoShareHtml = Resources.GalleryServer.UC_MoView_Tb_Share_Embed_Lbl,
        MoShareDwnld = Resources.GalleryServer.UC_MoView_Tb_Share_Download_Lbl,
        MoShareDwnldFile = Resources.GalleryServer.UC_MoView_Tb_Share_Download_Link,
        MoShareDwnldZip = Resources.GalleryServer.UC_MoView_Tb_Share_DownloadAlbum_Link,
        MoShareDwnldZipTt = Resources.GalleryServer.UC_MoView_Tb_Share_DownloadAlbum_Link_Tt,
        MoNoSsHdr = Resources.GalleryServer.UC_MoView_NoSs_Hdr,
        MoNoSsBdy = Resources.GalleryServer.UC_MoView_NoSs_Bdy,

        //MediaDeleteConfirm = Resources.GalleryServer.UC_MoView_Tb_Delete_Confirm,
        MetaEditPlaceholder = Resources.GalleryServer.UC_MoView_Meta_Edit_Placeholder,
        SyncStarting = Resources.GalleryServer.Task_Synch_Progress_SynchStarting,
        SyncAborting = Resources.GalleryServer.Task_Synch_Progress_SynchCanceling,
        SyncAbort = Resources.GalleryServer.Task_Synch_Cancel_Button_Text,

        RbnDelOrgTtHdr = Resources.GalleryServer.RbnDelOrgTtHdr,
        RbnDelOrgTtDtl = Resources.GalleryServer.RbnDelOrgTtDtl,
        RbnDelDbRcrdsTtHdr = Resources.GalleryServer.RbnDelDbRcrdsTtHdr,
        RbnDelDbRcrdsTtDtl = Resources.GalleryServer.RbnDelDbRcrdsTtDtl,

        RbnHome = Resources.GalleryServer.RbnHome,
        RbnManage = Resources.GalleryServer.RbnManage,
        RbnAdmin = Resources.GalleryServer.RbnAdmin,
        RbnSettings = Resources.GalleryServer.RbnSettings,
        RbnOpt = Resources.GalleryServer.RbnOpt,
        RbnOptTt = Resources.GalleryServer.RbnOptTt,
        RbnOrg = Resources.GalleryServer.RbnOrg,
        RbnOrgTt = Resources.GalleryServer.RbnOrgTt,
        RbnThmbSltAll = Resources.GalleryServer.RbnThmbSltAll,
        RbnThmbSltNone = Resources.GalleryServer.RbnThmbSltNone,
        RbnMediaSizeLbl = Resources.GalleryServer.RbnMediaSizeLbl,
        MediaSzThmb = Resources.GalleryServer.Site_MediaSzThmb,
        MediaSzOpt = Resources.GalleryServer.Site_MediaSzOpt,
        MediaSzOrg = Resources.GalleryServer.Site_MediaSzOrg,
        RbnUsrAbm = Resources.GalleryServer.RbnUsrAbm,
        RbnUsrAbmTt = Resources.GalleryServer.RbnUsrAbmTt,
        RbnSs = Resources.GalleryServer.RbnSs,
        RbnSsTt = Resources.GalleryServer.RbnSsTt,
        RbnSsOptns = Resources.GalleryServer.RbnSsOptns,
        RbnSsTypeLbl = Resources.GalleryServer.RbnSsTypeLbl,
        RbnSsTypeFs = Resources.GalleryServer.RbnSsTypeFs,
        RbnSsLoopLbl = Resources.GalleryServer.RbnSsLoopLbl,
        RbnSsTypeInline = Resources.GalleryServer.RbnSsTypeInline,
        RbnDl = Resources.GalleryServer.RbnDl,
        RbnDlTt = Resources.GalleryServer.RbnDlTt,
        ThmbSltAll = Resources.GalleryServer.Site_ThmbSltAll,
        ThmbSltNone = Resources.GalleryServer.Site_ThmbSltNone,
        RbnDlProcTt = Resources.GalleryServer.RbnDlProcTt,
        RbnSh = Resources.GalleryServer.RbnSh,
        RbnShTt = Resources.GalleryServer.RbnShTt,
        RbnShAsset = Resources.GalleryServer.RbnShAsset,
        RbnShAbm = Resources.GalleryServer.RbnShAbm,
        RbnShAssetUrlLbl = Resources.GalleryServer.RbnShAssetUrlLbl,
        RbnShUrlLbl = Resources.GalleryServer.RbnShUrlLbl,
        RbnShEmbedLbl = Resources.GalleryServer.RbnShEmbedLbl,
        RbnSt = Resources.GalleryServer.RbnSt,
        RbnStTt = Resources.GalleryServer.RbnStTt,
        RbnStUp = Resources.GalleryServer.RbnStUp,
        RbnStDn = Resources.GalleryServer.RbnStDn,
        RbnNewAbm = Resources.GalleryServer.RbnNewAbm,
        RbnNewAbmTt = Resources.GalleryServer.RbnNewAbmTt,
        RbnAddItems = Resources.GalleryServer.RbnAddItems,
        RbnAddItemsTt = Resources.GalleryServer.RbnAddItemsTt,
        RbnMoveItems = Resources.GalleryServer.RbnMoveItems,
        RbnMoveItemsTt = Resources.GalleryServer.RbnMoveItemsTt,
        RbnCopyItems = Resources.GalleryServer.RbnCopyItems,
        RbnCopyItemsTt = Resources.GalleryServer.RbnCopyItemsTt,
        RbnRpl = Resources.GalleryServer.RbnRpl,
        RbnRplTt = Resources.GalleryServer.RbnRplTt,
        RbnRplBtn = Resources.GalleryServer.RbnRplBtn,
        RbnRplTtHdr = Resources.GalleryServer.RbnRplTtHdr,
        RbnRplTtDtl = Resources.GalleryServer.RbnRplTtDtl,
        RbnDel = Resources.GalleryServer.RbnDel,
        RbnDelTt = Resources.GalleryServer.RbnDelTt,
        RbnDelOptns = Resources.GalleryServer.RbnDelOptns,
        RbnDelOrg = Resources.GalleryServer.RbnDelOrg,
        RbnDelDbOnly = Resources.GalleryServer.RbnDelDbOnly,
        RbnDelCnfrmTitle = Resources.GalleryServer.RbnDelCnfrmTitle,
        RbnDelOkBtn = Resources.GalleryServer.RbnDelOkBtn,
        CancelBtn = Resources.GalleryServer.Default_Task_Cancel_Button_Text,
        RbnThmb = Resources.GalleryServer.RbnThmb,
        RbnThmbTt = Resources.GalleryServer.RbnThmbTt,
        RbnThmbOptns = Resources.GalleryServer.RbnThmbOptns,
        RbnThmbTtHdr = Resources.GalleryServer.RbnThmbTtHdr,
        RbnThmbTtDtl = Resources.GalleryServer.RbnThmbTtDtl,
        RbnEdtImg = Resources.GalleryServer.RbnEdtImg,
        RbnEdtImgTt = Resources.GalleryServer.RbnEdtImgTt,
        RbnEdtRotLtTt = Resources.GalleryServer.RbnEdtRotLtTt,
        RbnEdtRotRtTt = Resources.GalleryServer.RbnEdtRotRtTt,
        RbnEdtFlipHTt = Resources.GalleryServer.RbnEdtFlipHTt,
        RbnEdtFlipVTt = Resources.GalleryServer.RbnEdtFlipVTt,
        RbnSec = Resources.GalleryServer.RbnSec,
        RbnSecTt = Resources.GalleryServer.RbnSecTt,
        RbnSecPvtAbm = Resources.GalleryServer.RbnSecPvtAbm,
        RbnSync = Resources.GalleryServer.RbnSync,
        RbnSyncTt = Resources.GalleryServer.RbnSyncTt,
        RbnUsrSettings = Resources.GalleryServer.RbnUsrSettings,
        RbnUsrSettingsTt = Resources.GalleryServer.RbnUsrSettingsTt,
        RbnMngUsers = Resources.GalleryServer.RbnMngUsers,
        RbnMngUsersTt = Resources.GalleryServer.RbnMngUsersTt,
        RbnMngRoles = Resources.GalleryServer.RbnMngRoles,
        RbnMngRolesTt = Resources.GalleryServer.RbnMngRolesTt,
        RbnQueue = Resources.GalleryServer.RbnQueue,
        RbnQueueTt = Resources.GalleryServer.RbnQueueTt,
        RbnUiTmpl = Resources.GalleryServer.RbnUiTmpl,
        RbnUiTmplTt = Resources.GalleryServer.RbnUiTmplTt,
        RbnMediaTmpl = Resources.GalleryServer.RbnMediaTmpl,
        RbnMediaTmplTt = Resources.GalleryServer.RbnMediaTmplTt,
        RbnGlryMgr = Resources.GalleryServer.RbnGlryMgr,
        RbnGlryMgrTt = Resources.GalleryServer.RbnGlryMgrTt,
        RbnCss = Resources.GalleryServer.RbnCss,
        RbnCssTt = Resources.GalleryServer.RbnCssTt,
        RbnBakRstr = Resources.GalleryServer.RbnBakRstr,
        RbnBakRstrTt = Resources.GalleryServer.RbnBakRstrTt,
        RbnEventLog = Resources.GalleryServer.RbnEventLog,
        RbnEventLogTt = Resources.GalleryServer.RbnEventLogTt,
        RbnSiteSettings = Resources.GalleryServer.RbnSiteSettings,
        RbnSiteSettingsTt = Resources.GalleryServer.RbnSiteSettingsTt,
        RbnGlrySettings = Resources.GalleryServer.RbnGlrySettings,
        RbnGlrySettingsTt = Resources.GalleryServer.RbnGlrySettingsTt,
        RbnGlryCtrlSettings = Resources.GalleryServer.RbnGlryCtrlSettings,
        RbnGlryCtrlSettingsTt = Resources.GalleryServer.RbnGlryCtrlSettingsTt,
        RbnAbmSettings = Resources.GalleryServer.RbnAbmSettings,
        RbnAbmSettingsTt = Resources.GalleryServer.RbnAbmSettingsTt,
        RbnMediaSettings = Resources.GalleryServer.RbnMediaSettings,
        RbnMediaSettingsTt = Resources.GalleryServer.RbnMediaSettingsTt,
        RbnImgSettings = Resources.GalleryServer.RbnImgSettings,
        RbnImgSettingsTt = Resources.GalleryServer.RbnImgSettingsTt,
        RbnVidAudSettings = Resources.GalleryServer.RbnVidAudSettings,
        RbnVidAudSettingsTt = Resources.GalleryServer.RbnVidAudSettingsTt,
        RbnMetaSettings = Resources.GalleryServer.RbnMetaSettings,
        RbnMetaSettingsTt = Resources.GalleryServer.RbnMetaSettingsTt,
        RbnFileTypeSettings = Resources.GalleryServer.RbnFileTypeSettings,
        RbnFileTypeSettingsTt = Resources.GalleryServer.RbnFileTypeSettingsTt,
        RbnGsEntTt = Resources.GalleryServer.RbnGsEntTt,
        RbnGsHmTt = Resources.GalleryServer.RbnGsHmTt,
      };
    }
  }
}